name: CI/CD - ASP.NET Core

on:
  push:
    branches:
      - main  # Roda o pipeline quando houver push na branch main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restaurar pacotes
        run: dotnet restore

      - name: Build da aplicação
        run: dotnet build --configuration Release --no-restore

      - name: Rodar testes (se houver)
        run: dotnet test --configuration Release --no-build || echo "Nenhum teste configurado"

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir e enviar a imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/seguranca-publica-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/seguranca-publica-api:latest
